# Generated by Django 4.2.11 on 2024-05-12 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_published",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
